---
  - name: Copy SSL certificates
    copy: src={{ item.src }} dest={{ item.dest }} owner={{ sc_owner }} group={{ sc_group }} mode={{ sc_mode }}
    when: ( stat_key.stat.exists and stat_cert.stat.exists )
    with_items:
      - { src: "{{ sc_cert_fn_local }}", dest: "{{ sc_cert_fn }}" }
      - { src: "{{ sc_key_fn_local }}", dest: "{{ sc_key_fn }}" }

  - name: Copy SSL certificate data
    copy: content={{ item.content }} dest={{ item.dest }} owner={{ sc_owner }} group={{ sc_group }} mode={{ sc_mode }}
    when: >
      ( sc_local_key_data is defined and sc_local_cert_data is defined )
    with_items:
      - { content: "{{ sc_local_cert_data|default }}", dest: "{{ sc_cert_fn }}" }
      - { content: "{{ sc_local_key_data|default }}", dest: "{{ sc_key_fn }}" }
    no_log: true
