---
  - name: Creating CSR and RSA key
    file: openssl req -nodes -sha256 -newkey rsa:{{ key_size }} -keyout {{ serverName }}.key -passout pass:'{{ passphrase }}' -out {{ sc_csr_fn }} -subj "{{ sc_subject }} creates={{ sc_csr_fn }}"

#  - name: Generate RSA key
#    command: openssl genrsa -out {{ sc_key_fn }} {{ key_size }} creates={{ sc_key_fn }}
#
#  - name: Generate CSR
#    command: openssl req -new -sha256 -subj "{{ sc_subject }}" -key {{ sc_key_fn }} -out {{ sc_csr_fn }} creates={{ sc_csr_fn }}

