---

# https://docs.mongodb.com/manual/tutorial/configure-x509-client-authentication/
# http://www.mad-hacking.net/documentation/linux/security/ssl-tls/creating-csr.xml

# Must have in SSL Configuration:
#
#   keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment, keyAgreement
#   extendedKeyUsage = clientAuth
#
# Defaults:
#   keyUsage = nonRepudiation, digitalSignature, keyEncipherment
#   # extendedKeyUsage = critical,timeStamping
#

  - name: Uncomment req_extensions
    replace: dest=/etc/ssl/openssl.cnf regexp='# req_extensions = v3_req' replace='req_extensions = v3_req' backup=yes
    become: true

  - name: Updating Client Config
    replace: dest=/etc/ssl/openssl.cnf regexp='# extendedKeyUsage = critical,timeStamping$' replace='extendedKeyUsage = clientAuth' backup=yes
    become: true

  - name: copy sample openssl.cnf file
    become: true
    connection: local
    copy:
      module: copy
      dest: /etc/ssl/openssl.cnf
      src: ../templates/openssl.cnf


