---
# This copies the CSR from the remote host to local, so that it can be supplied to the CA for submittal.

  - name: Ensure local path exists (pull csr)
    file: path="{{ sc_local_cert_path }}" state=directory
    connection: local

  - name: Copy CSR/Key to local private directory
    fetch: src={{ item.src }} dest={{ item.dest }} flat=yes
    become: true
    with_items:
      - { src: "{{ sc_csr_remote }}", dest: "{{ sc_csr_local }}" }
      - { src: "{{ sc_key_remote }}", dest: "{{ sc_key_local }}" }
